/* A JavaScript statement*/
//This will execute on the screen...
alert("Hello from, Ahkeem!");
//Document represents the current webpage...
//Write is a command that writes a message to the page...
document.write("<h1>Welcome to Javascript Basics</h1>");
alert("Thanks for visiting");
//outputs messages to the console...
console.log("Program complete");
